version: '3.8'

services:
  api:
    container_name: crud-contact-not-persistent-api
    image: crud-contact-not-persistent-api-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      # ✨ Target the dev stage
      target: dev
    # Mount host directory to docker container to support watch mode
    volumes:
      - .:/app
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      - /app/node_modules
    env_file:
      - .docker.env
    ports:
      - 5002:5002
    command: yarn start:dev
